files: "/*"

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        args: ["--config=pyproject.toml"]

      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
        args: ["--sp=setup.cfg"]

      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        args: [ "--config=setup.cfg" ]

      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [ python ]
        args: [ "--config-file=setup.cfg" ]